<a href="https://colab.research.google.com/github/Piyushydv08/Machine-Learning/blob/main/Day_28_Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('/content/covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [10]:
X_train

age  gender  fever   cough       city
31   83    Male  103.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
74   34  Female  104.0  Strong      Delhi
63   10    Male  100.0    Mild  Bangalore
8    19  Female  100.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
66   51    Male  104.0    Mild    Kolkata
85   16  Female  103.0    Mild  Bangalore
26   19  Female  100.0    Mild    Kolkata
45   72    Male   99.0    Mild  Bangalore
91   38    Male    NaN    Mild      Delhi

[80 rows x 5 columns]

## 1. Aam Zindagi

In [11]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [22]:
X_train_fever

array([[103.        ],
       [100.83561644],
       [104.        ],
       [100.        ],
       [100.        ],
       [100.        ],
       [100.83561644],
       [ 98.        ],
       [100.83561644],
       [103.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [103.        ],
       [ 99.        ],
       [ 99.        ],
       [100.        ],
       [101.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [100.83561644],
       [102.        ],
       [101.        ],
       [102.        ],
       [ 98

In [12]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [23]:
X_train_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [14]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [24]:
X_train_gender_city

array([[1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],


In [15]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [25]:
X_train_age

array([[83],
       [23],
       [34],
       [10],
       [19],
       [47],
       [42],
       [71],
       [84],
       [73],
       [66],
       [ 6],
       [14],
       [10],
       [68],
       [64],
       [69],
       [33],
       [80],
       [80],
       [64],
       [11],
       [27],
       [34],
       [42],
       [82],
       [13],
       [44],
       [48],
       [25],
       [60],
       [11],
       [42],
       [82],
       [16],
       [64],
       [ 5],
       [83],
       [20],
       [79],
       [20],
       [19],
       [74],
       [31],
       [55],
       [18],
       [24],
       [38],
       [60],
       [51],
       [12],
       [71],
       [34],
       [65],
       [27],
       [47],
       [49],
       [69],
       [14],
       [46],
       [19],
       [73],
       [40],
       [49],
       [34],
       [65],
       [69],
       [26],
       [ 5],
       [49],
       [12],
       [24],
       [75],
       [ 8],
       [51],
       [51],
       [16],

In [16]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [26]:
X_train_transformed

array([[ 83.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 23.        , 100.83561644,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 100.83561644,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 84.        , 100.83561644,   0.        ,   0.        ,
          0.    

## 2. Mentos Zindagi

In [17]:
from sklearn.compose import ColumnTransformer

In [19]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [20]:
transformer.fit_transform(X_train).shape

(80, 7)

In [28]:
transformer.fit_transform(X_train)

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.83561644,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.83561644,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [100.83561644,   0.        ,   0.        ,   0.        ,
          0.    

In [21]:
transformer.transform(X_test).shape

(20, 7)